In [24]:
import pandas as pd
import numpy as np

In [48]:
df = pd.read_csv('Final.csv')

In [50]:
df['Semestre'] = df['Semestre'].apply(lambda x: int(x.replace('º','').replace('°','')))

In [51]:
df['Lun'] = df['Lun'].apply(lambda x: x.replace('\n','') if type(x) != float else x)
df['Mar'] = df['Mar'].apply(lambda x: x.replace('\n','') if type(x) != float else x)
df['Mie'] = df['Mie'].apply(lambda x: x.replace('\n','') if type(x) != float else x)
df['Jue'] = df['Jue'].apply(lambda x: x.replace('\n','') if type(x) != float else x)
df['Vie'] = df['Vie'].apply(lambda x: x.replace('\n','') if type(x) != float else x)
df['Link'] = df['Link'].apply(lambda x: np.nan if x == 'E' else x)
df['Calificacion'] = df['Calificacion'].apply(lambda x: np.nan if (x == 'R') or (x=='ERROR') else float(x))

In [60]:
df.describe()

         Semestre  Ocupabilidad  Calificacion
count  191.000000    191.000000    159.000000
mean     4.837696     33.769634      6.766038
std      2.171549      9.317178      1.686387
min      1.000000     10.000000      3.200000
25%      3.000000     30.000000      5.750000
50%      5.000000     40.000000      7.000000
75%      7.000000     40.000000      7.900000
max      8.000000     40.000000     10.000000

In [66]:
df

,Semestre,Grupo,Clave,Unidad de aprendizaje,Academia,Lun,Mar,Mie,Jue,Vie,Profesor,Programa,Opcion,Departamento,Ocupabilidad,Link,Calificacion
0,1,1MV2,M104,GEOMETRÍA ANALÍTICA,AG,16:30-18:00,NaN,16:30-18:00,NaN,16:30-18:00,FÉLIX ZAMORA SÁNCHEZ,LIM,TRONCO COMÚN,INGENIERÍA Y CIENCIAS SOCIALES,40,https://www.misprofesores.com/profesores/FELIX...,6.0
1,1,1MV2,M101,SOCIEDAD Y CONOCLIMIENTO,CS,NaN,15:00-16:30,NaN,15:00-16:30,NaN,OSVALDO VILIULFO CÉSPEDES GAMA,LIM,TRONCO COMÚN,MATEMÁTICAS,40,https://www.misprofesores.com/profesores/osval...,5.3
2,1,1MV2,M102,CÁLCULO I,CA,15:00-16:30,NaN,15:00-16:30,NaN,15:00-16:30,ISABEL HERNÁNDEZ TÉLLEZ,LIM,TRONCO COMÚN,MATEMÁTICAS,40,https://www.misprofesores.com/profesores/Isabe...,8.6
3,1,1MV2,M105,INFORMÁTICA,I,18:00-19:30,NaN,18:00-19:30,18:00-19:30,NaN,ALFREDO GODÍNEZ MUÑOZ,LIM,TRONCO COMÚN,MATEMÁTICAS,40,https://www.misprofesores.com/profesores/Alfre...,3.5
4,1,1MV2,M103,ÁLGEBRA I,AG,NaN,16:30-18:00,NaN,16:30-18:00,18:00-19:30,ALFONSO GARCÍA MURILLO,LIM,TRONCO COMÚN,INGENIERÍA Y CIENCIAS SOCIALES,40,https://www.misprofesores.com/profesores/ALFON...,4.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,8,8FV1,836,ARQUITECTURA DE UNA COMPUTADORA,AG,16:30 -18:00,16:30 -18:00,NaN,16:30 -18:00,NaN,EDUARDO VIRUEÑA SILVA,LFM,MATEMÁTICAS,MATEMÁTICAS,30,https://www.misprofesores.com/profesores/Eduar...,7.4
187,8,8FV2,867,INTRODUCCION A FÍSICA NUCLEAR Y PARTICULAS ELE...,F,15:00-17:00,NaN,15:00-17:00,NaN,15:00-17:00,MIGUEL NERI ROSAS,LFM,ESP. FÍSICA,FÍSICA,20,https://www.misprofesores.com/profesores/migue...,7.7
188,8,8FV4,897,PROTECCIÓN RADIOLÓGICA,F,NaN,14:00-15:30,NaN,14:00-15:30,NaN,JULIÁN SÁNCHEZ GUTIÉRREZ,LFM,ING. NUCLEAR,FÍSICA,12,NaN,NaN
189,8,8FV4,895,INGENIERÍA NUCLEAR II,F,15:00-16:30,NaN,15:00-16:30,NaN,NaN,JOSÉ AGUSTÍN FRANCISCO RODRÍGUEZ PÉREZ,LFM,ING. NUCLEAR,FÍSICA,12,NaN,NaN
190,8,8FV4,896,TEORÍA DE REACTORES NUCLEARES II,F,NaN,16:30 -18:00,NaN,16:30 -18:00,NaN,MIGUEL ÁNGEL MARTÍNEZ FLORENTINO,LFM,ING. NUCLEAR,FÍSICA,12,https://www.misprofesores.com/profesores/MIGUE...,5.9

In [77]:
df.groupby(['Programa','Semestre','Grupo']).mean()

                         Ocupabilidad  Calificacion
Programa Semestre Grupo
LFM      1        1FV3      40.000000      7.750000
         2        2FM1      40.000000      7.175000
                  2FM2      40.000000      6.820000
                  2FV1      40.000000      7.040000
         3        3FM1      30.000000      7.700000
                  3FM2      30.000000      7.766667
                  3FV1      30.000000      7.625000
         4        4FM1      30.000000      6.333333
                  4FM2      28.666667      5.900000
                  4FV1      30.000000      9.400000
                  4FV2      28.666667      7.300000
         5        5FM1      35.000000      6.866667
                  5FM2      26.000000      5.550000
                  5FM3      10.000000      7.050000
                  5FV1      35.000000      7.900000
                  5FV2      26.000000      7.875000
                  5FV4      12.000000     10.000000
         6        6FM1      35.000000      5.825000
                  6FM2      26.400000      6.175000
                  6FV1      35.000000      6.300000
                  6FV2      30.000000      8.750000
                  6FV4      12.000000           NaN
         7        7FM1      35.000000      9.033333
                  7FM2      30.000000      7.525000
                  7FM3      10.000000      3.700000
                  7FV1      35.000000      5.550000
                  7FV2      20.000000      9.300000
                  7FV4      12.000000      5.900000
         8        8FM1      20.000000      8.200000
                  8FM2      22.400000      6.150000
                  8FM2A     20.000000           NaN
                  8FM3      10.000000      9.500000
                  8FM4      12.000000           NaN
                  8FV1      30.000000      7.250000
                  8FV2      20.000000      7.700000
                  8FV4      12.000000      5.900000
LIM      1        1MV2      40.000000      5.660000
         2        2MM1      40.000000      6.850000
                  2MV1      40.000000      6.350000
                  2MV2      40.000000      7.650000
         3        3MM1      40.000000      7.350000
                  3MM2      40.000000      6.325000
                  3MV1      40.000000      6.375000
         4        4MM1      40.000000      7.060000
                  4MV1      40.000000      5.900000
         5        5MM1      40.000000      5.266667
                  5MM2      40.000000      6.900000
                  5MV1      40.000000      6.020000
         6        6MM1      40.000000      6.175000
                  6MV1      40.000000      7.220000
                  6MV2      40.000000      7.400000
         7        7MM1      40.000000      4.875000
                  7MV1      40.000000      6.625000
                  7MV2      40.000000      5.800000
         8        8MM1      40.000000      4.800000
                  8MV1      40.000000      6.060000

In [70]:
sample = df.groupby(['Programa','Semestre','Grupo']).mean()

In [73]:
sample.to_excel('Promedios2.xlsx')

In [80]:
groups = []

for group in df['Grupo'].unique():
    groups.append(df[df['Grupo']== group])

In [102]:
df[df['Programa']=='LIM']['Grupo'].unique()

array(['1MV2', '2MM1', '2MV1', '2MV2', '3MM1', '3MM2', '3MV1', '4MM1',
       '4MV1', '5MM1', '5MM2', '5MV1', '6MM1', '6MV1', '6MV2', '7MM1',
       '7MV1', '7MV2', '8MM1', '8MV1'], dtype=object)

In [82]:
groups[1]

,Semestre,Grupo,Clave,Unidad de aprendizaje,Academia,Lun,Mar,Mie,Jue,Vie,Profesor,Programa,Opcion,Departamento,Ocupabilidad,Link,Calificacion
5,2,2MM1,M207,CÁLCULO II,CA,09:30-11:00,NaN,09:30-11:00,NaN,09:30-11:00,FAUSTO JARQUÍN ZARATE,LIM,TRONCO COMÚN,MATEMÁTICAS,40,https://www.misprofesores.com/profesores/Faust...,6.0
6,2,2MM1,M206,INTRODUCCIÓN A LA INGENIERÍA,I,NaN,08:00-09:30,NaN,08:00-09:30,NaN,FABIOLA CANTÚ HERNÁNDEZ,LIM,TRONCO COMÚN,INGENIERÍA Y CIENCIAS SOCIALES,40,NaN,NaN
7,2,2MM1,M209,MATEMÁTICAS DISCRETAS,AG,12:30-14:00,NaN,12:30-14:00,12:30-14:00,NaN,RUBÉN RAMÓN VARGAS PALOMARES,LIM,TRONCO COMÚN,MATEMÁTICAS,40,https://www.misprofesores.com/profesores/Ruben...,9.0
8,2,2MM1,M208,ÁLGEBRA II,AG,11:00-12:30,12:30-14:00,NaN,NaN,12:30-14:00,JOEL CRUZ RAMÍREZ,LIM,TRONCO COMÚN,MATEMÁTICAS,40,https://www.misprofesores.com/profesores/Joel-...,6.8
9,2,2MM1,M210,PROGRAMACIÓN,MA,NaN,11:00-12:30,11:00-12:30,11:00-12:30,NaN,ROGELIO CRUZ GARCÍA,LIM,TRONCO COMÚN,MATEMÁTICAS,40,https://www.misprofesores.com/profesores/Rogel...,5.6

In [86]:
unidades = []
for unidad in df['Unidad de aprendizaje'].unique():
    unidades.append(df[df['Unidad de aprendizaje']== unidad])

In [101]:
unidades[4]

,Semestre,Grupo,Clave,Unidad de aprendizaje,Academia,Lun,Mar,Mie,Jue,Vie,Profesor,Programa,Opcion,Departamento,Ocupabilidad,Link,Calificacion
4,1,1MV2,M103,ÁLGEBRA I,AG,NaN,16:30-18:00,NaN,16:30-18:00,18:00-19:30,ALFONSO GARCÍA MURILLO,LIM,TRONCO COMÚN,INGENIERÍA Y CIENCIAS SOCIALES,40,https://www.misprofesores.com/profesores/ALFON...,4.9
92,1,1FV3,102,ÁLGEBRA I,AG,19:30-21:00,18:30-20:00,NaN,19:30-21:00,NaN,ALFONSO GARCÍA MURILLO,LFM,TRONCO COMÚN,MATEMÁTICAS,40,https://www.misprofesores.com/profesores/ALFON...,4.9

In [100]:
df.to_csv('Cleande_df.csv')

In [107]:
df[df['Programa']=='LFM']['Grupo'].unique()

array(['1FV3', '2FM1', '2FM2', '2FV1', '3FM1', '3FM2', '3FV1', '4FM1',
       '4FM2', '4FV1', '4FV2', '5FM1', '5FM2', '5FM3', '5FV1', '5FV2',
       '5FV4', '6FM1', '6FM2', '6FV1', '6FV2', '6FV4', '7FM1', '7FM2',
       '7FM3', '7FV1', '7FV2', '7FV4', '8FM1', '8FM2', '8FM2A', '8FM3',
       '8FM4', '8FV1', '8FV2', '8FV4'], dtype=object)

In [109]:
df[df['Unidad de aprendizaje'] == 'ÁLGEBRA II']

,Semestre,Grupo,Clave,Unidad de aprendizaje,Academia,Lun,Mar,Mie,Jue,Vie,Profesor,Programa,Opcion,Departamento,Ocupabilidad,Link,Calificacion
8,2,2MM1,M208,ÁLGEBRA II,AG,11:00-12:30,12:30-14:00,NaN,NaN,12:30-14:00,JOEL CRUZ RAMÍREZ,LIM,TRONCO COMÚN,MATEMÁTICAS,40,https://www.misprofesores.com/profesores/Joel-...,6.8
13,2,2MV1,M208,ÁLGEBRA II,AG,16:30-18:00,NaN,16:30-18:00,NaN,16:30-18:00,CARLOS ALEJANDRO MORENO MUÑOZ,LIM,TRONCO COMÚN,MATEMÁTICAS,40,https://www.misprofesores.com/profesores/Carlo...,7.6
15,2,2MV2,M208,ÁLGEBRA II,AG,15:00-16:30,NaN,15:00-16:30,NaN,15:00-16:30,MARCO ANTONIO RODRÍGUEZ ANDRADE,LIM,TRONCO COMÚN,MATEMÁTICAS,40,https://www.misprofesores.com/profesores/Marco...,7.5
97,2,2FM1,207,ÁLGEBRA II,AG,12:30-14:00,12:30-14:00,NaN,12:30-14:00,NaN,ABELARDO SANTAELLA QUINTAS,LFM,TRONCO COMÚN,MATEMÁTICAS,40,https://www.misprofesores.com/profesores/Abela...,7.2
100,2,2FM2,207,ÁLGEBRA II,AG,08:00-09:30,NaN,08:00-09:30,NaN,08:00-09:30,HUGO MÉNDEZ DELGADILLO,LFM,TRONCO COMÚN,MATEMÁTICAS,40,https://www.misprofesores.com/profesores/HUGO-...,7.0
106,2,2FV1,207,ÁLGEBRA II,AG,NaN,18:00-19:30,NaN,18:00-19:30,19:30-21:00,IGNACIO HERMELINDO OTERO RUBIO,LFM,TRONCO COMÚN,MATEMÁTICAS,40,https://www.misprofesores.com/profesores/IGNAC...,7.9